[package]
name = "local-channel"
version = "0.1.3"
description = "A non-threadsafe multi-producer, single-consumer, futures-aware, FIFO queue"
authors = [
    "Nikolay Kim <cjfdndsla4@gmail.com>",
    "Rob Ede <kbank100147116498@icloud.com>",
]
repository = "https://github.com/actix/actix-net.git"
keywords = ["channel", "local", "futures"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
futures-core = { version = "0.3.7", default-features = true}
futures-sink = { version = "0.3.7", default-features = false }
futures-util = { version = "0.3.7", default-features = true }
local-waker = "0.1"

[dev-dependencies]
tokio = { version = "1.13.1", features = ["rt", "macros"] }
